sudo: required
services:
  - docker

before_install:
  - docker build -t thedsk8/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thedsk8/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  environment: "Docker-env" # whatever your name is
  bucket_name: "elasticbeanstalk-ap-southeast-1-372296733353"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY